spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
    password: 123123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true